### ISSUE TITLE
ARN is MISSING

### ISSUE THREAD

**Issue by sneakykiwi** [aws-actions/amazon-ecs-deploy-task-definition#369]
Hello, 

I am trying to setup CI/CD for an ECS cluster and I am getting the following error when trying to deploy the ecs task definition.

To my eyes it makes no sense as thisi arn literally exists and I can see it. Anyone have any thoughts?

```Error: arn:aws:ecs:eu-central-1:***:service/cyphrspace is MISSING```

**Comment by kushal-ti** [comment]
I'm also getting the exact same error

**Comment by yamaoto** [comment]
Any updates here?

**Comment by kushal-ti** [comment]
In my case it turned out to be a really dumb mistake on my part. the ECS cluster name environment variable that you're supposed to be specifying should just be the name of the cluster, and not the entire ARN. the action constructs the ARN for you based on environment variables provided by you such as AWS_REGION and cluster/service name

**Comment by yamaoto** [comment]
Got it. For my case it just I thought that my service will be created automatically from task-definition, but when I created my service in the aws console everything worked
