### ISSUE TITLE
Auto-assign public IP is disabled

### ISSUE THREAD

**Issue by Elijen** [aws-actions/amazon-ecs-deploy-task-definition#43]
I am using this action as part of the "Deploy to Amazon ECS" template offered by GitHub Actions but the workflow keeps pending at "Deploy Amazon ECS task definition" step.

After inspecting stopped tasks in my cluster I have found the error: 
```
CannotPullContainerError: Error response from daemon: Get https://****.dkr.ecr.eu-west-1.amazonaws.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

I can see `Public IP: --` under task details, while this article: https://aws.amazon.com/premiumsupport/knowledge-center/ecs-pull-container-api-error-ecr/ recommends setting `Auto-assign public IP` to `ENABLED`

Is there a way I can modify this GH action to pass enable public IP parameter?

**Comment by clareliguori** [comment]
Since the `assignPublicIp` field is an ECS service-level attribute (and not in the task definition), this action doesn't support deploying that field.  It should be a one-time change though to use the console or `aws ecs update-service` to flip that on for your service.  Alternatively, you could use the AWS CLI in the GitHub Actions environment to script it.

**Comment by Elijen** [comment]
@clareliguori I think there is an option to pass `assignPublicIp` also on task run but I have solved the problem by creating a new service (AWS didn't let me change this on an existing one for some reason). Thanks!
